# ===============================
# Cloudinary Credentials
# ===============================
[cloudinary]
cloud_name = "dqqoqmvbs"
api_key = "111437321178856"
api_secret = "9yWvotYfb0CVYDH1ySdfJUfA0Ok"

# ===============================
# Google Service Account (untuk gspread / Google Sheets)
# Copy dari file JSON yang kamu download
# ===============================
[gcp_service_account]
type = "service_account"
project_id = "myproject-id"
private_key_id = "1234567890abcdef1234567890abcdef12345678"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBK...\n-----END PRIVATE KEY-----\n"
client_email = "my-service@myproject.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/my-service%40myproject.iam.gserviceaccount.com"

# ===============================
# Google Sheet target (opsional)
# ===============================
[gspread]
sheet_url = "https://docs.google.com/spreadsheets/d/1AbCdEfGhIjKlMnOpQrStUvWxYz1234567890/edit"
