[cloudinary]
cloud_name = "dqqoqmvbs"
api_key = "111437321178856"
api_secret = "9yWvotYfb0CVYDH1ySdfJUfA0Ok"

[gcp_service_account]
type = "service_account"
project_id = "penyakit-daun-tebu"
private_key_id = "c80f0d0a84d61839794516747e45a6c5aac1eb41"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCa3XDgJNAotoz1
TnPN5qLjSi2T48njKgnKjatCEFxuNMY+ibK03v743zkT69PtB4uFlcuyla7l22B5
0FM4mNyyd6oO54bepOplsxBErxSSo0vy9sX1usHuF+Dl7cFsL0q+fqrYtV7oSkuj
...
x2kK2wJQkUBGsC2Oocbp0Q==
-----END PRIVATE KEY-----"""
client_email = "sheets-access@penyakit-daun-tebu.iam.gserviceaccount.com"
client_id = "112403982517019963313"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access%40penyakit-daun-tebu.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gspread]
sheet_url = "https://docs.google.com/spreadsheets/d/1AbCdEfGhIjKlMnOpQrStUvWxYz1234567890/edit"
